package com.york.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

//mark it entity using Entity annotation 
//map table name using Table annoation
@Entity
@Table(name = "books")
public class Book implements Serializable {

	private int id;
	private String name;

	public Book() {
	}

	// mark id as primary key with autogenerated value
	// map database column id with id field
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setId(int id) {
		this.id = id;
	}

}
